/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fineral' at '1/14/17 10:56 PM' with Gradle 2.14.1
 *
 * @author fineral, @date 1/14/17 10:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
